#!/usr/bin/env bash
set -e
git clone --recursive https://github.com/KarypisLab/SLIM.git
cd /SLIM/lib/GKlib
make config openmp=set
make
cd ../../
make config shared=1 cc=gcc cxx=gcc prefix=~/.local
make install
cd python-package
python3.10 setup.py install --user